name: ruggerifrontend
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_native_splash: ^2.3.5
  flutter_localizations:
    sdk: flutter
  shimmer: ^2.0.0
  get:  ^4.1.4
  file_picker: ^6.1.1
  flutter_dropzone: ^3.0.6
  collection: ^1.15.0
  intl: ^0.18.1
  dotted_border: ^2.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Urbane
      fonts:
        - asset: assets/fonts/Urbane-Bold.ttf
        - asset: assets/fonts/Urbane-BoldItalic.ttf
        - asset: assets/fonts/Urbane-DemiBold.ttf
        - asset: assets/fonts/Urbane-DemiBoldItalic.ttf
        - asset: assets/fonts/Urbane-ExtraLight.ttf
        - asset: assets/fonts/Urbane-ExtraLightItalic.ttf
        - asset: assets/fonts/Urbane-Heavy.ttf
        - asset: assets/fonts/Urbane-HeavyItalic.ttf
        - asset: assets/fonts/Urbane-Light.ttf
        - asset: assets/fonts/Urbane-LightItalic.ttf
        - asset: assets/fonts/Urbane-Medium.ttf
        - asset: assets/fonts/Urbane-MediumItalic.ttf
        - asset: assets/fonts/Urbane-Thin.ttf
        - asset: assets/fonts/Urbane-ThinItalic.ttf
        
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
